# Generated by Django 2.1.12 on 2019-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('path_to_binary', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('app_type_id', models.CharField(choices=[('1', 'Aplicación WEB'), ('2', 'APP Android'), ('3', 'APP iOS')], max_length=1)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
