# Generated by Django 2.1.12 on 2019-09-20 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_NAME', models.CharField(max_length=200, verbose_name='Nombre')),
                ('AT_ID', models.CharField(choices=[('1', 'Aplicación WEB'), ('2', 'APP Android'), ('3', 'APP iOS')], max_length=1, verbose_name='Tipo de aplicación')),
                ('A_DESCRIPTION', models.TextField(verbose_name='Descripción')),
                ('A_PATH_TO_BINARY', models.CharField(max_length=200, verbose_name='Link')),
                ('U_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='APP_TESTING_ROUND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E2ET_PATH_TO_SCRIPT', models.CharField(max_length=200, verbose_name='Nombre')),
                ('E2ET_HEADLESS', models.BooleanField(verbose_name='¿Es Headless?')),
                ('ATR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ATR_APP', to='aplicaciones.APP')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='E2E_TEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E2ET_PATH_TO_SCRIPT', models.CharField(max_length=200, verbose_name='Path del script')),
                ('E2ET_HEADLESS', models.BooleanField()),
                ('ATR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='E2E_ATR', to='aplicaciones.APP_TESTING_ROUND')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
