# Generated by Django 2.1.12 on 2019-09-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-id'], 'verbose_name': 'Aplicación', 'verbose_name_plural': 'Aplicaciones'},
        ),
    ]
