# Generated by Django 2.1.12 on 2019-09-20 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_auto_20190919_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='RANDOM_TEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RT_NUM_EVENTS', models.PositiveIntegerField(verbose_name='Número de eventos')),
                ('RT_DURATION', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Random Test',
                'verbose_name_plural': 'Random Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='app_testing_round',
            options={'ordering': ['-id'], 'verbose_name': 'App Testing Round', 'verbose_name_plural': 'App Testing Rounds'},
        ),
        migrations.AlterModelOptions(
            name='e2e_test',
            options={'ordering': ['-id'], 'verbose_name': 'E2E Test', 'verbose_name_plural': 'E2E Tests'},
        ),
        migrations.RenameField(
            model_name='app_testing_round',
            old_name='E2ET_PATH_TO_SCRIPT',
            new_name='ATR_NAME',
        ),
        migrations.RemoveField(
            model_name='app_testing_round',
            name='E2ET_HEADLESS',
        ),
        migrations.AddField(
            model_name='app_testing_round',
            name='ATR_PROGRAMMED_EXECUTION',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='e2e_test',
            name='E2ET_HEADLESS',
            field=models.BooleanField(verbose_name=''),
        ),
        migrations.AddField(
            model_name='random_test',
            name='ATR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RT_ATR', to='aplicaciones.APP_TESTING_ROUND'),
        ),
    ]
