# Generated by Django 2.1.12 on 2019-09-20 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0003_auto_20190919_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_testing_round',
            name='ATR_PROGRAMMED_EXECUTION',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='random_test',
            name='RT_DURATION',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
